# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Myphp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://safiacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_93911bd422b842bf8be8dc3315b46b2e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b7291958370d426884fb3bf7d729f647 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: safiacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_93911bd422b842bf8be8dc3315b46b2e }}/ubuntu:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Myphp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a340cb7019e143218cd4f01fc227ae1b }}
        images: 'safiacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_93911bd422b842bf8be8dc3315b46b2e }}/ubuntu:${{ github.sha }}'